#!/usr/bin/env python3

import sys

def collatz(num):
    print(num)
    if (num != 1):
       if num % 2:
           collatz(3 * num + 1)
       else:
           collatz(num // 2)

while True:
    print('Enter an integer:', end=' ')
    try:
        number = int(input())
        collatz(number)
        print('')
    except KeyboardInterrupt:
        print()
        sys.exit()
    except ValueError:
        print('Error: Invalid argument')
