#!/usr/bin/env python3

#I realized I never actually wrote down my own OOP example
#in Python so I could have my own example for my notes

class animal:
	age = 0
	size = ''

class dog(animal):
	name = ''
	def __init__(self, name, age, size):
		self.name = name
		self.age = age
		self.size = size
	def speak(self):
		print("hi my name is", self.name, "I am", self.size, "and I am", self.age, "years old")

holly = dog('holly', 9, 'small')
holly.speak()
